# Generated by Django 5.0.6 on 2024-05-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='compact_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/compact_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='s3_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
