# Generated by Django 5.0.6 on 2024-05-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0002_alter_image_compact_image_alter_image_s3_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_size',
            field=models.FloatField(default=0.0),
        ),
    ]
