# Generated by Django 5.0.6 on 2024-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0003_alter_folder_size_alter_image_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
