# Generated by Django 5.0.6 on 2024-05-21 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0004_folder_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='previous_folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='added_to_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='added_to_trash_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='added_to_trash_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='previous_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_folder', to='image_gallery_app.folder'),
        ),
        migrations.AlterField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='image_gallery_app.folder'),
        ),
    ]
