# Generated by Django 5.0.6 on 2024-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0005_remove_folder_previous_folder_folder_added_to_trash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
