# Generated by Django 5.0.6 on 2024-06-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0006_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_uuid', models.CharField(max_length=40, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=220, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('downloaded_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
