# Generated by Django 5.0.6 on 2024-06-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0007_downloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover_page/<django.db.models.fields.CharField>/'),
        ),
    ]
