# Generated by Django 5.0.6 on 2024-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0008_folder_cover_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='cover_page',
        ),
        migrations.AddField(
            model_name='folder',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover_photo/<django.db.models.fields.CharField>/'),
        ),
    ]
