# Generated by Django 5.0.6 on 2024-06-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery_app', '0009_remove_folder_cover_page_folder_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover_photo/'),
        ),
    ]
